### ISSUE TITLE
ERROR:root:Error processing image {'source': 'shapes', 'yaml_path': 

### ISSUE THREAD

**Issue by musematics** [YDS-FOREVER/Mask_RCNN-master--TrainOwerDatset#2]
/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py:75: RuntimeWarning: invalid value encountered in reduce
  ret = umr_sum(arr, axis, dtype, out, keepdims)
ERROR:root:Error processing image {'source': 'shapes', 'yaml_path': '../../data/info.yaml', 'width': 256, 'path': '../../data/train/image/fsave1038.png', 'mask_path': '../../data/train/label1/fsave1038.png', 'id': 209, 'height': 256}
Traceback (most recent call last):
  File "/home/wangzhe/data/segmentation/MaskRCNN/mrcnn/model.py", line 1707, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/wangzhe/data/segmentation/MaskRCNN/mrcnn/model.py", line 1229, in load_image_gt
    mode=config.IMAGE_RESIZE_MODE)
  File "/home/wangzhe/data/segmentation/MaskRCNN/mrcnn/utils.py", line 458, in resize_image
    order=1, mode="constant", preserve_range=True)
  File "/usr/local/lib/python2.7/dist-packages/skimage/transform/_warps.py", line 165, in resize
    tform.estimate(src_corners, dst_corners)
  File "/usr/local/lib/python2.7/dist-packages/skimage/transform/_geometric.py", line 679, in estimate
    _, _, V = np.linalg.svd(A)
  File "/usr/local/lib/python2.7/dist-packages/numpy/linalg/linalg.py", line 1562, in svd
    u, s, vh = gufunc(a, signature=signature, extobj=extobj)
  File "/usr/local/lib/python2.7/dist-packages/numpy/linalg/linalg.py", line 98, in _raise_linalgerror_svd_nonconvergence
    raise LinAlgError("SVD did not converge")
LinAlgError: SVD did not converge

It seems something went wrong with my input data. Does anyone know how to fix this? Thanks a lot.
In Chinese: 感觉是输入图片出现了问题，不知道有没有人知道该如何解决？感谢各位大神

**Comment by musematics** [comment]
The problem is solved. It is because my 'yaml' document is in different format, so that one of the class in stead of '_background_' is deleted. Thus the input is abnormal. For a problem like this, the cause is mostly with the input dataset, either 'label' or 'image'.
In Chinese： 问题已经解决，输入的yaml文件格式不太一样导致我把‘背景’类别删掉了，一般这类问题往往是由数据集中图片或者标签有问题引起
